version: "3.9"  # optional since v1.27.0

services:

  stage:
    profiles: ["simulator"]
    image: iocchi/stage_environments
    container_name: stage
    network_mode: "host"
    tty: true
    environment:
    - DISPLAY=:0
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/home/robot/.Xauthority
    - $HOME/src/stage_environments:/home/robot/src/stage_environments
    entrypoint:
    - bash
    - -ci
    - "rosrun stage_environments start_simulation.py --server -server_port 9235"

  orazio:
    profiles: ["robot"]
    image: iocchi/orazio
    container_name: orazio
    restart: always
    privileged: true
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - /dev:/dev
    - $HOME/src/marrtino_apps:/home/robot/src/marrtino_apps

  orazio2018:
    profiles: ["robot2018"]
    image: iocchi/orazio:2018
    container_name: orazio
    restart: always
    privileged: true
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - /dev:/dev
    - $HOME/src/marrtino_apps:/home/robot/src/marrtino_apps

  orazioarm:
    profiles: ["robotarm64"]
    image: iocchi/orazio:arm64
    container_name: orazio
    restart: always
    privileged: true
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - /dev:/dev
    - $HOME/src/marrtino_apps:/home/robot/src/marrtino_apps

  orazio2018arm:
    profiles: ["robot2018arm64"]
    image: iocchi/orazio:2018-arm64
    container_name: orazio
    restart: always
    privileged: true
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - /dev:/dev
    - $HOME/src/marrtino_apps:/home/robot/src/marrtino_apps

  base:
    image: marrtino:base
    build:
      context: $MARRTINO_APPS_HOME/docker
      dockerfile: Dockerfile.base
    container_name: base
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $HOME/src/marrtino_apps:/home/robot/src/marrtino_apps
    - $HOME/log:/home/robot/log

  teleop:
    image: marrtino:teleop
    build:
      context: $MARRTINO_APPS_HOME/docker
      dockerfile: Dockerfile.teleop
    container_name: teleop
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - /dev:/dev
    - $HOME/src/marrtino_apps:/home/robot/src/marrtino_apps

  navigation:
    image: marrtino:navigation
    build:
      context: $MARRTINO_APPS_HOME/docker
      dockerfile: Dockerfile.navigation
    container_name: navigation
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $HOME/src/marrtino_apps:/home/robot/src/marrtino_apps

  nginx:
    image: nginx
    profiles: ["local"]
    container_name: nginx
    network_mode: "host"
    volumes:
    - $HOME/src/marrtino_apps/www:/usr/share/nginx/html

