system:
  nginx: off

simulator:
  stage: off

robot:
  motorboard: off  # MARRtinoMB2019  # ArduinoMotorShield
  4wd: off
  joystick: off
  laser: off
  camera: off
  
functions:
  navigation: off
  vision: off
  speech: off
  mapping: off
  social: off

